import {test,expect} from '@playwright/test';

test('TC-0903 screenshot capture persists extraction and post source',async({page,request})=>{
 await page.route('**/api/assistant/images/*/extract',route=>route.fulfill({json:{text:'截图观点：机械专业适合某些岗位。'}}));
 await page.goto('/');await page.getByRole('button',{name:'助理',exact:true}).click();await page.getByRole('button',{name:'💡 想法',exact:true}).click();
 await page.locator('input[type=file]').setInputFiles({name:'post.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nAAAAABJRU5ErkJggg==','base64')});
 await expect(page.getByAltText('待保存截图')).toBeVisible();await page.getByText('帖子来源（选填）',{exact:true}).click();await page.getByLabel('帖子标题').fill('专业讨论截图');await page.getByLabel('帖子链接').fill('https://example.com/original');await page.getByRole('button',{name:'保存想法',exact:true}).click();await expect(page.getByAltText('待保存截图')).toHaveCount(0);
 const state=await(await request.get('/api/assistant/state')).json();const thought=state.unassigned.find((s:any)=>s.source_title==='专业讨论截图');expect(thought.raw_text).toContain('截图观点');expect(thought.source_url).toBe('https://example.com/original');
});

test('TC-0901 toggles, drafts, multiline and latest question first',async({page,request})=>{
 await page.goto('/');await page.getByRole('button',{name:'助理',exact:true}).click();
 const input=page.getByLabel('告诉助理');await page.getByRole('button',{name:'💡 想法',exact:true}).click();
 const text='键盘 '+Date.now();await input.fill(text);await input.press('Control+Enter');await input.pressSequentially('second line');await expect(input).toHaveValue(text+'\nsecond line');await input.dispatchEvent('keydown',{key:'Enter',isComposing:true});await expect(input).toHaveValue(text+'\nsecond line');
 await page.getByRole('button',{name:'💡 想法',exact:true}).click();await expect(input).toHaveValue('');await page.getByRole('button',{name:'💡 想法',exact:true}).click();await expect(input).toHaveValue(text+'\nsecond line');await input.press('Enter');await expect(input).toHaveValue('');
 const state=await(await request.get('/api/assistant/state')).json();expect(state.unassigned.some((t:any)=>t.raw_text===text+'\nsecond line')).toBe(true);
 await page.getByRole('button',{name:'💡 想法',exact:true}).click();await input.fill('今天先做什么？');await input.press('Enter');await expect(page.locator('.conversation-message.assistant').first()).toContainText('本地推荐');await input.fill('所有未完成任务');await input.press('Enter');await expect(page.locator('.conversation-message.user').first()).toContainText('所有未完成任务');
});
test('TC-0902 cards, sources, metadata, editing, backdrop and history',async({page,request})=>{
 const topic=await(await request.post('/api/assistant/topics',{data:{title:'简历 '+Date.now()}})).json();
 await request.post('/api/assistant/thoughts',{data:{text:'按岗位调整项目经历',topicId:topic.id,sourceTitle:'帖子A',sourceUrl:'https://example.com/a'}});
 let detail=await(await request.get('/api/assistant/topics/'+topic.id)).json();await request.patch('/api/assistant/topics/'+topic.id,{data:{revision:detail.topic.revision,summary:'## 岗位匹配\n\n根据岗位调整简历。'}});
 await page.goto('/');await page.getByRole('button',{name:'知识库',exact:true}).click();await expect(page.getByLabel('知识导图')).toHaveCount(0);await page.locator('.library-entry').filter({hasText:topic.title}).click();await expect(page.getByRole('heading',{name:'岗位匹配',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'编辑正文',exact:true}).click();await page.getByLabel('笔记主题').fill('秋招');await page.getByRole('button',{name:'保存正文'}).click();await page.getByText(/^来源（/).click();await expect(page.getByRole('link',{name:'打开原帖'})).toHaveAttribute('href','https://example.com/a');
 await page.getByRole('button',{name:'编辑正文'}).click();await page.getByLabel('编辑整理稿').fill('## 修改步骤\n\n先读岗位要求。');await page.getByRole('button',{name:'保存正文'}).click();await expect(page.getByRole('heading',{name:'修改步骤'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'知识详情'})).toHaveCount(0);
 await page.locator('.library-entry').filter({hasText:'修改步骤'}).click();await page.locator('.drawer-backdrop').click({position:{x:5,y:5}});await expect(page.getByRole('dialog',{name:'知识详情'})).toHaveCount(0);await page.screenshot({path:'.test-data/library-029.png',fullPage:true});
});
test('TC-0904 task layout and schedule cancellation undo',async({page,request})=>{
 const title='待办 '+Date.now();await request.post('/api/tasks',{data:{task:{title,startAt:'2099-01-01',deadlineAt:'2099-01-03'}}});
 const event=(await(await request.post('/api/personal/schedule',{data:{title:'旧面试 '+Date.now(),start_at:'2020-01-01'}})).json()).item;
 await page.goto('/');await expect(page.getByRole('button',{name:'帮我排优先级'})).toHaveCount(0);await expect(page.getByRole('button',{name:'打开周挂件'})).toBeVisible();await expect(page.locator('.later-column')).toContainText(title);await page.getByText('过去或未安排的固定事项',{exact:true}).click();await page.getByRole('button',{name:new RegExp(event.title)}).click();await page.getByRole('button',{name:'取消事项',exact:true}).click();await expect(page.getByRole('dialog',{name:'事项详情'})).toHaveCount(0);await page.getByRole('button',{name:'撤销',exact:true}).click();await page.getByText('过去或未安排的固定事项',{exact:true}).click();await expect(page.getByRole('button',{name:new RegExp(event.title)})).toBeVisible();await page.screenshot({path:'.test-data/tasks-029.png',fullPage:true});
});
test('TC-0905 week calendar dots and bars; widget chat',async({page,request})=>{
 const day=new Date(),start=new Date(day.getFullYear(),day.getMonth(),day.getDate()),end=new Date(start);end.setDate(end.getDate()+2);
 const local=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 await request.post('/api/personal/schedule',{data:{title:'跨天测试',start_at:local(start),end_at:local(end)}});await request.post('/api/tasks',{data:{task:{title:'单日测试',startAt:local(start)}}});
 await page.goto('/?view=week');await expect(page.locator('.dot-event').filter({hasText:'单日测试'})).toBeVisible();await expect(page.locator('.span-event').filter({hasText:'跨天测试'}).first()).toBeVisible();await page.screenshot({path:'.test-data/week-029.png',fullPage:true});
 await page.getByRole('button',{name:'助理',exact:true}).click();await page.getByLabel('告诉助理').fill('今天先做什么？');await page.getByRole('button',{name:'发送',exact:true}).click();await expect(page.locator('.conversation-message.assistant').first()).toContainText('本地推荐');await page.getByRole('button',{name:'返回周计划'}).click();await expect(page.getByPlaceholder('输入一个任务……')).toBeVisible();
});

test('TC-0910/0911 all tasks persist in left pane and editable titles preserve dates',async({page,request})=>{
 const title='未来任务 '+Date.now();const response=await(await request.post('/api/tasks',{data:{task:{title,startAt:'2099-01-01',deadlineAt:'2099-01-03'}}})).json();
 await page.goto('/');await expect(page.locator('.quick-plan-date')).toHaveCount(0);await page.getByText(title,{exact:true}).click();await page.getByRole('button',{name:title,exact:true}).click();await page.getByLabel('任务名称',{exact:true}).fill('');await page.getByRole('button',{name:'保存名称'}).click();await expect(page.getByRole('alert')).toContainText('不能为空');await page.getByLabel('任务名称',{exact:true}).fill('取消修改');await page.getByLabel('任务名称',{exact:true}).press('Escape');await expect(page.getByRole('button',{name:title,exact:true})).toBeVisible();await page.getByRole('button',{name:title,exact:true}).click();await page.getByLabel('任务名称',{exact:true}).fill(title+'已改');await page.getByLabel('任务名称',{exact:true}).press('Enter');await expect(page.getByRole('button',{name:title+'已改',exact:true})).toBeVisible();
 await page.goto('/?view=week');const card=page.locator('.calendar-task-list button').filter({hasText:title+'已改'});await expect(card).toBeVisible();await expect(card).toContainText('2099-01-01');
 const split=page.getByRole('separator');await split.focus();await page.keyboard.press('ArrowRight');await page.reload();await expect(split).toHaveAttribute('aria-valuenow','37');
 await card.click();await page.getByRole('button',{name:title+'已改',exact:true}).click();await page.getByLabel('任务名称',{exact:true}).fill(title+'周修改');await page.getByRole('button',{name:'保存名称'}).click();await expect(page.getByRole('button',{name:title+'周修改',exact:true})).toBeVisible();await page.getByRole('button',{name:'关闭详情'}).click();
 const before=await(await request.get('/api/tasks/planning')).json();const task=before.tasks.find((t:any)=>t.title===title+'周修改');expect(task.deadline_at).toBe('2099-01-03');expect(task.start_at).toBe('2099-01-01');
 const source=page.locator('.calendar-task-list button').filter({hasText:title+'周修改'});const target=page.locator('.week-day-row.is-today');await source.dragTo(target);await expect(source).not.toContainText('计划 2099-01-01');const after=await(await request.get('/api/tasks/'+task.id+'/details')).json();expect(after.task.deadline_at).toBe('2099-01-03');await page.screenshot({path:'.test-data/week-0210.png',fullPage:true});
});

test('TC-0912 old multi-point topic displays separate cards without unrelated detail',async({page,request})=>{
 const topic=await(await request.post('/api/assistant/topics',{data:{title:'秋招卡片 '+Date.now()}})).json();
 const points=[{title:'根据JD调整简历',chapter:'简历',kind:'idea',text:'对照JD补充匹配的真实经历。',sourceIds:[]},{title:'确定求职方向',chapter:'求职方向',kind:'idea',text:'先明确自己想投递的目标岗位。',sourceIds:[]}];
 await page.route('**/api/assistant/state',async route=>{const r=await route.fetch(),data=await r.json();data.topics=data.topics.map((t:any)=>t.id===topic.id?{...t,category:'秋招',points_json:JSON.stringify(points)}:t);await route.fulfill({response:r,json:data});});
 await page.route('**/api/assistant/topics/'+topic.id,async route=>{const r=await route.fetch(),data=await r.json();data.topic={...data.topic,category:'秋招',points_json:JSON.stringify(points)};await route.fulfill({response:r,json:data});});
 await page.goto('/');await page.getByRole('button',{name:'知识库',exact:true}).click();await expect(page.getByLabel('知识导图')).toHaveCount(0);await page.locator('.library-entry').filter({hasText:'根据JD调整简历'}).click();await expect(page.locator('.notebook-drawer .knowledge-prose')).toContainText('对照JD');await expect(page.locator('.notebook-drawer .knowledge-prose')).not.toContainText('目标岗位');await page.getByRole('button',{name:'关闭详情'}).click();await page.screenshot({path:'.test-data/library-0210.png',fullPage:true});
});

test('TC-0913 seven rows include empty days and navigate by week',async({page})=>{
 await page.goto('/?view=week');await expect(page.locator('.week-day-row')).toHaveCount(7);await expect(page.locator('.week-day-row').first()).toContainText('周一');await expect(page.locator('.week-day-row').last()).toContainText('周日');const date=await page.locator('.week-day-row').first().getAttribute('data-date');await page.getByRole('button',{name:'下一周',exact:true}).click();await expect(page.locator('.week-day-row').first()).not.toHaveAttribute('data-date',date!);await page.getByRole('button',{name:'今天',exact:true}).click();await expect(page.locator('.week-day-row.is-today')).toHaveCount(1);await page.screenshot({path:'.test-data/week-0211.png',fullPage:true});
});

test('TC-0914 old knowledge drags into category and undo retains content',async({page,request})=>{
 const suffix=Date.now();await request.post('/api/personal/knowledge',{data:{kind:'note',title:'旧内容 '+suffix,category:'旧分类',content:'原始内容必须保留'}});await request.post('/api/personal/knowledge',{data:{kind:'note',title:'目标卡片 '+suffix,category:'目标分类',content:'目标正文'}});
 await page.goto('/');await page.getByRole('button',{name:'知识库',exact:true}).click();await expect(page.getByRole('button',{name:'新建笔记'})).toHaveCount(0);const source=page.locator('.library-entry').filter({hasText:'旧内容 '+suffix});const target=page.locator('.knowledge-category').filter({has:page.getByRole('heading',{name:'目标分类',exact:true})});await source.dragTo(target.getByRole('heading'));await expect(target).toContainText('旧内容 '+suffix);await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.locator('.knowledge-category').filter({has:page.getByRole('heading',{name:'旧分类',exact:true})})).toContainText('旧内容 '+suffix);
});

test('TC-0915 conversational review persists and exports only explicitly',async({page,request})=>{
 const title='面试复盘任务 '+Date.now();await request.post('/api/tasks',{data:{task:{title}}});await page.goto('/');await page.getByText(title,{exact:true}).click();await page.getByRole('button',{name:'复盘这件事',exact:true}).click();await expect(page.getByRole('region',{name:'复盘',exact:true})).toBeVisible();await expect(page.locator('.review-facts')).toContainText(title);await page.getByLabel('复盘补充').fill('介绍贡献时不够清楚');await page.getByRole('button',{name:'发送补充'}).click();await expect(page.getByLabel('实际情况')).toHaveValue('介绍贡献时不够清楚');await page.getByLabel('原因判断').fill('没有提前整理自己的职责');await page.getByLabel('下次调整').fill('准备一分钟个人贡献介绍 '+title);await page.getByLabel('可保留的经验').fill('提前按职责、行动、结果组织介绍');await page.getByRole('button',{name:'保存复盘',exact:true}).click();await page.getByRole('button',{name:'加入任务',exact:true}).click();await expect(page.getByRole('button',{name:'已加入任务',exact:true})).toBeDisabled();await page.getByLabel('经验保存大类').fill('秋招');await page.getByRole('button',{name:'存为经验',exact:true}).click();await expect(page.getByRole('button',{name:'已存为经验',exact:true})).toBeDisabled();await page.screenshot({path:'.test-data/review-0211.png',fullPage:true});await page.getByRole('button',{name:'返回助理',exact:true}).click();await page.getByRole('button',{name:'复盘记录',exact:true}).click();await page.locator('.review-history button').filter({hasText:title}).click();await expect(page.getByLabel('原因判断')).toHaveValue('没有提前整理自己的职责');
});

test('TC-0916 directory creates persistent empty categories, renames and accepts card drops',async({page,request})=>{
 const suffix=Date.now(),name='自学 '+suffix,renamed='学习 '+suffix,title='移动卡片 '+suffix;
 await request.post('/api/personal/knowledge',{data:{kind:'note',title,category:'拖动来源',content:'保留正文'}});
 await page.goto('/');await page.getByRole('button',{name:'知识库',exact:true}).click();await page.getByRole('button',{name:'＋添加大类',exact:true}).click();await page.getByLabel('大类名称',{exact:true}).fill(name);await page.getByRole('button',{name:'保存大类',exact:true}).click();await expect(page.getByLabel('定位大类 '+name,{exact:true})).toContainText('0');
 await page.reload();await page.getByRole('button',{name:'知识库',exact:true}).click();await expect(page.getByLabel('定位大类 '+name,{exact:true})).toBeVisible();await page.getByLabel('管理大类 '+name,{exact:true}).click();await page.getByRole('button',{name:'重命名',exact:true}).click();await page.getByLabel('新的大类名称',{exact:true}).fill(renamed);await page.getByRole('button',{name:'保存大类',exact:true}).click();await expect(page.getByLabel('定位大类 '+renamed,{exact:true})).toBeVisible();
 await page.locator('.library-entry').filter({hasText:title}).dragTo(page.getByLabel('定位大类 '+renamed,{exact:true}));await expect(page.getByLabel('定位大类 '+renamed,{exact:true})).toContainText('1');await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.getByLabel('定位大类 '+renamed,{exact:true})).toContainText('0');
 await page.getByLabel('定位大类 '+renamed,{exact:true}).click();await expect(page.locator('.category-directory')).toHaveCSS('position','sticky');await expect(page.locator('.knowledge-category').filter({has:page.getByRole('heading',{name:renamed,exact:true})})).toBeInViewport();await expect(page.locator('.library-entry').filter({hasText:title})).toHaveCount(1);await page.screenshot({path:'.test-data/library-0212.png'});
});

test('TC-0917 manually delete empty and populated categories without deleting knowledge',async({page,request})=>{
 const id=Date.now(),empty='空大类 '+id,source='待删除 '+id,target='接收 '+id,title='保留知识 '+id;
 for(const name of [empty,source,target])await request.post('/api/assistant/categories',{data:{name}});
 await request.post('/api/personal/knowledge',{data:{kind:'note',title,category:source,content:'完整内容'}});
 await page.goto('/');await page.getByRole('button',{name:'知识库',exact:true}).click();await page.getByLabel('管理大类 '+empty,{exact:true}).click();await page.getByRole('button',{name:'删除大类',exact:true}).click();await expect(page.getByLabel('定位大类 '+empty,{exact:true})).toHaveCount(0);
 await page.getByLabel('管理大类 '+source,{exact:true}).click();await page.getByRole('button',{name:'删除大类',exact:true}).click();await expect(page.getByRole('button',{name:'移动并删除大类',exact:true})).toBeDisabled();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.getByLabel('定位大类 '+source,{exact:true})).toBeVisible();
 await page.getByLabel('管理大类 '+source,{exact:true}).click();await page.getByRole('button',{name:'删除大类',exact:true}).click();await page.getByLabel('删除大类后移动到').selectOption(target);await expect(page.getByRole('button',{name:'移动并删除大类',exact:true})).toBeInViewport();await page.screenshot({path:'.test-data/category-delete-0213.png'});await page.getByRole('button',{name:'移动并删除大类',exact:true}).click();await expect(page.getByLabel('定位大类 '+source,{exact:true})).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'知识库',exact:true}).click();await expect(page.getByLabel('定位大类 '+source,{exact:true})).toHaveCount(0);await expect(page.getByLabel('定位大类 '+empty,{exact:true})).toHaveCount(0);await expect(page.locator('.knowledge-category').filter({has:page.getByRole('heading',{name:target,exact:true})})).toContainText(title);
});
