import {CategoryDirectory} from './CategoryDirectory';
import {ReviewPanel} from './ReviewPanel';
import React,{useEffect,useRef,useState} from 'react';
import {captureKey,changed} from './interactions';
import {Markdown} from './KnowledgeMap';

import {knowledgeCards,cardTitle} from '../domain/knowledgeCards';

interface Topic {id:string;title:string;category:string|null;kind:string;revision:number;summary:string;points_json:string;paused:number;dirty_at:string|null;last_error:string|null}
interface Thought {id:string;raw_text:string;topic_id:string|null;source_title?:string;source_author?:string;source_url?:string;images?:{id:string}[]}
interface Detail {topic:Topic;thoughts:Thought[];versions:{id:string;summary:string;created_at:string}[]}
interface Ref {id:string;label:string;url?:string;topicId?:string;text?:string}
interface State {categories:{name:string;count:number}[];preferences:{aiEnabled:boolean;autoOrganize:boolean;configured:boolean};topics:Topic[];unassigned:Thought[];messages:{id:number;role:string;content:string;references_json?:string}[]}
interface Props {initialReviewTask?:string;view?:'capture'|'library';initialQuestion?:string;initialTopic?:string;onOpenTopic?:(id:string)=>void;onAsk?:(id:string,title:string)=>void;legacy?:{id:string;title:string;kind:string;category:string|null;content:string|null}[];onOpenLegacy?:(item:any)=>void}
async function call<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch('/api/assistant'+path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'请求失败');if(method!=='GET')changed(data);return data;}
export function AssistantPanel({view='capture',initialQuestion,initialTopic,initialReviewTask,onOpenTopic,onAsk,legacy=[],onOpenLegacy}:Props){
  const libraryRef=useRef<HTMLDivElement>(null);
  const [activeCategory,setActiveCategory]=useState('');
  const [reviewRequest,setReviewRequest]=useState<{title?:string;taskId?:string;history?:boolean}|null>(null);
  const [state,setState]=useState<State|null>(null),[detail,setDetail]=useState<Detail|null>(null),[selected,setSelected]=useState('');
  const [mode,setMode]=useState<'chat'|'idea'|'capture'>('chat'),[input,setInput]=useState(''),[category,setCategory]=useState('');
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
  const [pointIndex,setPointIndex]=useState(0),[pointTitle,setPointTitle]=useState(''),[pointChapter,setPointChapter]=useState(''),[pointCategory,setPointCategory]=useState('');
  const [draft,setDraft]=useState<string|null>(null),[editRevision,setEditRevision]=useState(0),[history,setHistory]=useState(false),[addition,setAddition]=useState('');
  const [metadata,setMetadata]=useState<{title:string;category:string;kind:string;revision:number}|null>(null),[mergeTarget,setMergeTarget]=useState('');
  const [sourceTitle,setSourceTitle]=useState(''),[sourceAuthor,setSourceAuthor]=useState(''),[sourceUrl,setSourceUrl]=useState('');
  const [images,setImages]=useState<{id:string;extractedText:string|null}[]>([]),[vision,setVision]=useState({baseUrl:'',model:'',apiKey:''});
  const [saved,setSaved]=useState(''),[reference,setReference]=useState<Ref|null>(null);
  const drafts=useRef({chat:'',idea:'',capture:''}),inputRef=useRef<HTMLTextAreaElement>(null),lock=useRef(false),selection=useRef(''),requestId=useRef<{key:string;id:string}|null>(null);
  async function refresh(){const next=await call<State>('/state');setState(next);if(selection.current){const id=selection.current;const d=await call<Detail>('/topics/'+id);if(selection.current===id)setDetail(d);}}
  useEffect(()=>{void refresh().catch(e=>setMessage(e.message));void call<{baseUrl:string;model:string}>('/vision').then(v=>setVision({...v,apiKey:''}));const timer=setInterval(()=>void refresh().catch(()=>{}),15000);const fn=()=>void refresh().catch(()=>{});window.addEventListener('assistant-changed',fn);return()=>{clearInterval(timer);window.removeEventListener('assistant-changed',fn);};},[]);
  async function select(id:string,index=0){setPointIndex(index);selection.current=id;setSelected(id);setDetail(null);setDraft(null);setMetadata(null);setHistory(false);if(id){try{const d=await call<Detail>('/topics/'+id);if(selection.current===id)setDetail(d);}catch(e){setMessage(String(e));}}}
  useEffect(()=>{if(initialTopic&&initialTopic!=='unassigned')void select(initialTopic);if(initialQuestion){if(initialQuestion.includes('复盘')){setReviewRequest({title:initialQuestion,taskId:initialReviewTask});}else{setMode('chat');setInput(initialQuestion);}}},[initialTopic,initialQuestion]);
  function close(){if((draft!==null||metadata||addition.trim())&&!window.confirm('还有未保存内容，确定关闭？'))return;void select('');setAddition('');}
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(reference)setReference(null);else if(detail&&view==='library')close();}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[detail,draft,metadata,addition,reference]);
  async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await fn();await refresh();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{lock.current=false;setBusy(false);requestAnimationFrame(()=>inputRef.current?.focus());}}
  function toggle(next:'idea'|'capture'){drafts.current[mode]=input;const value=mode===next?'chat':next;setMode(value);setInput(drafts.current[value]);setMessage('');}
  useEffect(()=>{const fn=()=>{drafts.current[mode]=input;setMode('capture');setInput(drafts.current.capture);};window.addEventListener('assistant-record-task',fn);return()=>window.removeEventListener('assistant-record-task',fn);},[mode,input]);
  async function upload(files:File[]){await run(async()=>{if(images.length+files.length>6)throw new Error('一次最多保存 6 张图片。');const added:{id:string;extractedText:string|null}[]=[];for(const file of files){if(file.size>5*1024*1024)throw new Error('单张图片不能超过 5 MB。');const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});added.push(await call<{id:string;extractedText:string|null}>('/images','POST',{dataUrl}));}setImages(old=>[...old,...added]);setMessage('图片已暂存。点亮“想法”后保存到知识库。');});}
  async function send(e:React.FormEvent){e.preventDefault();if(!input.trim()&&!images.length)return;if(mode==='chat'&&input.includes('复盘')){setReviewRequest({title:input});return;}await run(async()=>{
    if(mode==='idea'){
      const extracted:string[]=[];for(const image of images){const text=image.extractedText??(await call<{text:string}>('/images/'+image.id+'/extract','POST')).text;image.extractedText=text;extracted.push(text);}
      const text=[input,...extracted.map((s,i)=>`图片 ${i+1} 识别内容：\n${s}`)].filter(Boolean).join('\n\n');
      const body={text,category,topicId:null,sourceTitle,sourceAuthor,sourceUrl,imageIds:images.map(i=>i.id)};const key=JSON.stringify(body);if(requestId.current?.key!==key)requestId.current={key,id:crypto.randomUUID()};
      const result=await call<Thought>('/thoughts','POST',{...body,requestId:requestId.current.id});requestId.current=null;setImages([]);setSourceTitle('');setSourceAuthor('');setSourceUrl('');setSaved(result.topic_id||'unassigned');setMessage('原文已保存。'+(result.topic_id?'已加入所选小类。':'AI 开启自动整理后会归类，可在知识库查看。'));
    }else if(mode==='capture'){if(images.length)throw new Error('图片请切换到“想法”保存；任务使用文字描述。');const r=await call<{summary:string}>('/capture','POST',{text:input});setMessage(r.summary);}
    else{if(images.length)throw new Error('请先点亮“想法”保存并识别图片，再向助理提问。');await call('/chat','POST',{text:input,topicId:selected||undefined});}
    setInput('');drafts.current[mode]='';
  });}
  const categories=[...new Set([...(state?.categories??[]).map(c=>c.name),...(state?.topics??[]).flatMap(t=>knowledgeCards(t).map(p=>p.category||t.category||t.title)),...legacy.map(t=>t.category||'其他')])];
  const directory=categories.map(name=>({name,count:(state?.categories??[]).find(c=>c.name===name)?.count??0}));
  function jumpCategory(name:string){const sections=Array.from(libraryRef.current?.querySelectorAll<HTMLElement>('[data-category]')??[]);const target=name?sections.find(el=>el.dataset.category===name):libraryRef.current;target?.scrollIntoView({behavior:'smooth',block:'start'});setActiveCategory(name);}
  function dropCategory(e:React.DragEvent,group:string){e.preventDefault();try{const item=JSON.parse(e.dataTransfer.getData('application/x-knowledge-card'));void run(async()=>{await call('/cards/move','POST',{...item,category:group});setMessage('已移动到“'+group+'”，可撤销。');});}catch{setMessage('请拖动知识卡片。');}}
  useEffect(()=>{if(view!=='library')return;let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!libraryRef.current?.getClientRects().length)return;const sections=Array.from(libraryRef.current.querySelectorAll<HTMLElement>('[data-category]'));const current=sections.filter(el=>el.getBoundingClientRect().top<=120).at(-1)||sections[0];if(current)setActiveCategory(current.dataset.category||'');});};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[view,categories.join('|')]);
  const topics=state?.topics.filter(t=>[t.title,t.category,t.summary,t.points_json].join(' ').toLowerCase().includes(search.toLowerCase()))??[];
  const visibleLegacy=legacy.filter(t=>[t.title,t.category,t.content].join(' ').toLowerCase().includes(search.toLowerCase()));
  const cards=topics.flatMap(t=>knowledgeCards(t).map((point,index)=>({topic:t,point,index,group:point.category||t.category||t.title})));
  const activePoint=detail?knowledgeCards(detail.topic)[pointIndex]:undefined;
  const cardSources=detail?(activePoint?.sourceIds.length?detail.thoughts.filter(t=>activePoint.sourceIds.includes(t.id)):detail.thoughts):[];
  const pairs=[];for(let i=0;i<(state?.messages.length??0);i+=2)pairs.push(state!.messages.slice(i,i+2));
  function sourceCards(list:Thought[]){return list.map(t=><div className="source-card" key={t.id}><strong>{t.source_title||'手动记录 / 截图'}</strong>{t.source_author?<small>作者：{t.source_author}</small>:null}{t.source_url?<a href={t.source_url} target="_blank" rel="noreferrer">打开原帖</a>:null}<p>{t.raw_text}</p>{t.images?.map(im=><a key={im.id} href={'/api/assistant/images/'+im.id} target="_blank" rel="noreferrer"><img alt="来源截图" src={'/api/assistant/images/'+im.id}/></a>)}<label>移动到<select value={t.topic_id??''} onChange={e=>void run(async()=>{await call('/thoughts/'+t.id,'PATCH',{topicId:e.target.value||null});})}><option value="">待整理</option>{state?.topics.map(p=><option key={p.id} value={p.id}>{p.category||'其他'} / {p.title}</option>)}</select></label></div>);}
  if(reviewRequest&&view==='capture')return <ReviewPanel {...reviewRequest} onClose={()=>setReviewRequest(null)}/>;
  return <section className="assistant-panel" aria-label="对话与主题笔记">
    <header className="assistant-heading"><div><h2>{view==='library'?'知识库':'助理'}</h2><p>{view==='library'?'看清结构，积累自己的知识。':'默认问答；点亮想法或任务，开始记录。'}</p></div><details className="assistant-preferences"><summary>AI 与自动整理设置</summary><label><input type="checkbox" aria-label="助理 AI" checked={state?.preferences.aiEnabled??false} onChange={e=>void run(async()=>{await call('/preferences','PATCH',{aiEnabled:e.target.checked});})}/>AI</label><label><input type="checkbox" aria-label="自动整理" checked={state?.preferences.autoOrganize??false} onChange={e=>{const enabled=e.target.checked;void run(async()=>{await call('/preferences','PATCH',{autoOrganize:enabled});});}}/>自动整理</label><small>相关文字发送给文字模型。图片仅在识别时发送给下方配置的视觉模型。</small><details><summary>图片识别设置</summary><label>兼容接口地址<input value={vision.baseUrl} placeholder="https://服务商地址/v1" onChange={e=>setVision({...vision,baseUrl:e.target.value})}/></label><label>视觉模型名称<input value={vision.model} onChange={e=>setVision({...vision,model:e.target.value})}/></label><label>API Key<input type="password" autoComplete="off" value={vision.apiKey} placeholder="留空保留已存密钥" onChange={e=>setVision({...vision,apiKey:e.target.value})}/></label><button disabled={busy} onClick={()=>void run(async()=>{await call('/vision','POST',vision);setVision({...vision,apiKey:''});setMessage('图片识别设置已保存。');})}>保存图片设置</button></details></details></header>
    {view==='capture'?<><div className="review-entry"><button onClick={()=>setReviewRequest({title:'本周复盘'})}>本周复盘</button><button onClick={()=>setReviewRequest({history:true})}>复盘记录</button></div><form className="assistant-compose" onSubmit={e=>void send(e)}>
      <div className="capture-toggles"><button type="button" aria-pressed={mode==='idea'} disabled={busy} onClick={()=>toggle('idea')}>💡 想法</button><button type="button" aria-pressed={mode==='capture'} disabled={busy} onClick={()=>toggle('capture')}>✓ 任务</button><small>{mode==='chat'?'正在问答':mode==='idea'?'正在记录想法':'正在记录任务'}</small>{selected?<button type="button" onClick={()=>void select('')}>参考范围：{detail?.topic.title||'当前笔记'} ×</button>:null}</div>
      {mode==='idea'?<label>大类<input list="knowledge-categories" placeholder="自动分类，可新建大类" value={category} onChange={e=>setCategory(e.target.value)}/><datalist id="knowledge-categories">{categories.map(c=><option key={c}>{c}</option>)}</datalist></label>:null}
      <textarea ref={inputRef} aria-label="告诉助理" rows={4} maxLength={mode==='idea'?8000:4000} disabled={busy} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>captureKey(e,setInput)} onPaste={e=>{const files=Array.from(e.clipboardData.files);if(files.length){e.preventDefault();void upload(files);}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(Array.from(e.dataTransfer.files));}} placeholder="问问题、记录想法，或粘贴截图……"/>
      <div className="image-previews">{images.map(im=><div key={im.id}><img alt="待保存截图" src={'/api/assistant/images/'+im.id}/><button type="button" onClick={()=>setImages(old=>old.filter(i=>i.id!==im.id))}>移除</button></div>)}</div>
      <div className="assistant-controls"><label className="attachment-button">＋图片<input type="file" accept="image/png,image/jpeg,image/webp" multiple hidden disabled={busy} onChange={e=>{void upload(Array.from(e.target.files??[]));e.target.value='';}}/></label><small>Enter 提交 · Ctrl+Enter 换行</small><button disabled={busy||(!input.trim()&&!images.length)}>{busy?'处理中…':mode==='idea'?'保存想法':mode==='capture'?'保存任务':'发送'}</button></div>
      {mode==='idea'?<details><summary>帖子来源（选填）</summary><input aria-label="帖子标题" placeholder="帖子标题" value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)}/><input aria-label="帖子作者" placeholder="作者" value={sourceAuthor} onChange={e=>setSourceAuthor(e.target.value)}/><input aria-label="帖子链接" placeholder="原帖链接；截图无法自动还原链接" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></details>:null}
    </form>{mode==='chat'?<div className="assistant-conversation">{pairs.reverse().map(pair=><div className="conversation-pair" key={pair[0].id}>{pair.map(m=><div key={m.id} className={'conversation-message '+m.role}><strong>{m.role==='user'?'你':'助理'}</strong><Markdown text={m.content}/>{(JSON.parse(m.references_json||'[]') as Ref[]).map(r=><button className="source-chip" key={r.id} onClick={()=>setReference(r)}>{r.label}</button>)}</div>)}</div>)}</div>:null}</>:<>
      <div className="library-toolbar"><input aria-label="搜索知识库" placeholder="搜索分类、标题或知识" value={search} onChange={e=>setSearch(e.target.value)}/></div>
      <div className="library-layout"><CategoryDirectory categories={directory} active={activeCategory} onJump={jumpCategory} onDrop={dropCategory} onSave={async(name,from)=>{await call('/categories',from?'PATCH':'POST',{name,from});await refresh();setSearch('');}}/><div ref={libraryRef} className="knowledge-categories">{categories.map(group=><section data-category={group} key={group} className="knowledge-category" onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-knowledge-card')){e.preventDefault();e.currentTarget.classList.add('drag-over');}}} onDragLeave={e=>e.currentTarget.classList.remove('drag-over')} onDrop={e=>{e.currentTarget.classList.remove('drag-over');dropCategory(e,group);}}><h3>{group}</h3>{!cards.some(c=>c.group===group)&&!visibleLegacy.some(t=>(t.category||'其他')===group)?<p className="category-empty">{search?'没有匹配的知识':'暂无知识，可将卡片拖到这里'}</p>:null}<div className="library-list">{cards.filter(c=>c.group===group).map(({topic:t,point,index})=><button className="library-entry" key={t.id+':'+index} draggable onDragStart={e=>e.dataTransfer.setData('application/x-knowledge-card',JSON.stringify({kind:'topic',id:t.id,index,revision:t.revision}))} onClick={()=>void select(t.id,index)}><strong>{cardTitle(point)}</strong><small>{point.chapter&&!['主要想法','已明确的决定','待明确的问题','不同方案'].includes(point.chapter)?point.chapter:(t.category?t.title:'知识')}{t.dirty_at?' · 待整理':''}</small><p>{point.text.replace(/[#*`]/g,'').slice(0,110)||'暂无正文，点击编辑'}</p></button>)}{visibleLegacy.filter(t=>(t.category||'其他')===group).map(t=><button key={t.id} className="library-entry" draggable onDragStart={e=>e.dataTransfer.setData('application/x-knowledge-card',JSON.stringify({kind:'legacy',id:t.id}))} onClick={()=>onOpenLegacy?.(t)}><strong>{t.title}</strong><small>{t.category||'其他'} · 原有知识</small></button>)}</div></section>)}</div></div>
      <details className="unassigned-thoughts" open={initialTopic==='unassigned'||undefined}><summary>待整理（{state?.unassigned.length??0}）</summary><button disabled={busy} onClick={()=>void run(async()=>{await call('/classify/retry','POST');setMessage('已重新加入归类队列。请开启 AI 和自动整理。');})}>重试自动分类</button>{sourceCards(state?.unassigned??[])}</details>
    </>}
    {message?<p role="status" className="assistant-notice">{message}{saved&&onOpenTopic?<button onClick={()=>onOpenTopic(saved)}>查看保存位置</button>:null}</p>:null}
    {view==='library'&&detail?<div className="drawer-backdrop" onClick={e=>{if(e.target===e.currentTarget)close();}}><aside className="task-drawer notebook-drawer" role="dialog" aria-label="知识详情"><button onClick={close}>关闭详情</button><small>{activePoint?.category||detail.topic.category||detail.topic.title}</small><h3>{activePoint?cardTitle(activePoint):detail.topic.title}</h3>{detail.topic.last_error?<p role="alert">{detail.topic.last_error}</p>:null}<div className="assistant-controls">
      <button disabled={busy||Boolean(detail.topic.paused)||!state?.preferences.aiEnabled} onClick={()=>void run(async()=>{await call('/topics/'+selected+'/organize','POST');})}>现在整理</button><button onClick={()=>{setDraft(activePoint?.text||detail.topic.summary);setPointTitle(activePoint?cardTitle(activePoint):detail.topic.title);setPointChapter(activePoint?.chapter||'');setPointCategory(activePoint?.category||detail.topic.category||detail.topic.title);setEditRevision(detail.topic.revision);}}>编辑正文</button><button onClick={()=>onAsk?.(selected,detail.topic.title)}>就此提问</button></div>
      {metadata?<form onSubmit={e=>{e.preventDefault();void run(async()=>{await call('/topics/'+selected,'PATCH',metadata);setMetadata(null);});}}><label>笔记名称<input aria-label="笔记名称" value={metadata.title} onChange={e=>setMetadata({...metadata,title:e.target.value})}/></label><label>大类<input aria-label="笔记主题" value={metadata.category} onChange={e=>setMetadata({...metadata,category:e.target.value})}/></label><label>类型<select aria-label="笔记类型" value={metadata.kind} onChange={e=>setMetadata({...metadata,kind:e.target.value})}><option value="note">知识</option><option value="sop">SOP</option><option value="skill">技能</option></select></label><button>保存名称与分类</button><button type="button" onClick={()=>setMetadata(null)}>取消</button></form>:null}
      {draft!==null?<><label>笔记标题<input aria-label="知识点标题" value={pointTitle} onChange={e=>setPointTitle(e.target.value)}/></label><label>大类<input aria-label="笔记主题" value={pointCategory} onChange={e=>setPointCategory(e.target.value)}/></label><label>小类标签<input aria-label="小类标签" value={pointChapter} onChange={e=>setPointChapter(e.target.value)}/></label><textarea aria-label="编辑整理稿" rows={14} value={draft} onChange={e=>setDraft(e.target.value)}/><button disabled={busy} onClick={()=>void run(async()=>{await call('/topics/'+selected,'PATCH',{revision:editRevision,pointIndex,point:{title:pointTitle,text:draft,chapter:pointChapter,category:pointCategory}});setDraft(null);})}>保存正文</button><button onClick={()=>setDraft(null)}>取消编辑</button><small>手动编辑后暂停 AI 改写，避免覆盖。</small></>:<Markdown text={activePoint?.text||'内容已保存，整理后在这里显示完整正文。'}/>}
      <details><summary>来源（{cardSources.length}）</summary>{sourceCards(cardSources)}</details>
      <form className="notebook-addition" onSubmit={e=>{e.preventDefault();if(addition.trim())void run(async()=>{const key=JSON.stringify({addition,selected});if(requestId.current?.key!==key)requestId.current={key,id:crypto.randomUUID()};await call('/thoughts','POST',{text:addition,topicId:selected,requestId:requestId.current.id});requestId.current=null;setAddition('');});}}><label>补充想法<textarea aria-label="补充想法" value={addition} onChange={e=>setAddition(e.target.value)} onKeyDown={e=>captureKey(e,setAddition)}/></label><button disabled={busy||!addition.trim()}>保存补充</button></form>
      <details><summary>整理管理</summary><button disabled={busy} onClick={()=>void run(async()=>{await call('/topics/'+selected,'PATCH',{revision:detail.topic.revision,paused:!detail.topic.paused});})}>{detail.topic.paused?'恢复自动整理':'暂停自动改写'}</button><button onClick={()=>setHistory(!history)}>历史版本</button>{knowledgeCards(detail.topic).length===1?<><label>合并到<select value={mergeTarget} onChange={e=>setMergeTarget(e.target.value)}><option value="">选择另一小类</option>{state?.topics.filter(t=>t.id!==selected).map(t=><option value={t.id} key={t.id}>{t.category} / {t.title}</option>)}</select></label><button disabled={!mergeTarget||busy} onClick={()=>{if(window.confirm('将原文合并到目标小类，保留旧稿，是否继续？'))void run(async()=>{await call('/topics/'+selected+'/merge','POST',{targetId:mergeTarget});await select(mergeTarget);setMergeTarget('');});}}>合并，保留来源</button></>:<small>这是旧笔记拆出的独立卡片；可在编辑正文中单独修改大类和小类。</small>}</details>
      {history?<div className="topic-history">{detail.versions.map(v=><details key={v.id}><summary>{new Date(v.created_at).toLocaleString()}</summary><Markdown text={v.summary}/><button disabled={busy} onClick={()=>void run(async()=>{await call('/topics/'+selected,'PATCH',{revision:detail.topic.revision,restoreId:v.id});})}>恢复此版本并暂停自动改写</button></details>)}</div>:null}
    </aside></div>:null}
    {reference?<div className="drawer-backdrop" onClick={e=>{if(e.target===e.currentTarget)setReference(null);}}><aside className="task-drawer" role="dialog" aria-label="回答来源"><button onClick={()=>setReference(null)}>关闭来源</button><h3>{reference.label}</h3>{reference.url?<a href={reference.url} target="_blank" rel="noreferrer">打开原帖</a>:null}<p>{reference.text||'此引用来自现有事项。'}</p>{reference.topicId?<button onClick={()=>{onOpenTopic?.(reference.topicId!);setReference(null);}}>查看知识正文</button>:null}</aside></div>:null}
  </section>;
}
