import React,{useState} from 'react';
interface Props {categories:{name:string;count:number}[];active:string;onJump:(name:string)=>void;onDrop:(e:React.DragEvent,name:string)=>void;onDelete:(from:string,to?:string)=>Promise<void>;onSave:(name:string,from?:string)=>Promise<void>}
export function CategoryDirectory({categories,active,onJump,onDrop,onSave,onDelete}:Props){
 const [deleting,setDeleting]=useState<string|null>(null),[target,setTarget]=useState('');
 async function remove(from:string,to?:string){if(busy)return;setBusy(true);setError('');try{await onDelete(from,to);setDeleting(null);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const [editing,setEditing]=useState<string|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function edit(from:string){setDeleting(null);setEditing(from);setName(from);setError('');}
 return <aside className="category-directory" aria-label="大类目录"><strong>大类目录</strong><nav aria-label="知识分类"><button className="category-jump" onClick={()=>onJump('')}>全部知识 <small>{categories.reduce((n,c)=>n+c.count,0)}</small></button><div className="category-links">{categories.map(c=><div className="category-link" key={c.name} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-knowledge-card')){e.preventDefault();e.currentTarget.classList.add('drag-over');}}} onDragLeave={e=>e.currentTarget.classList.remove('drag-over')} onDrop={e=>{e.currentTarget.classList.remove('drag-over');onDrop(e,c.name);}}><button className="category-jump" aria-label={'定位大类 '+c.name} aria-current={active===c.name?'location':undefined} onClick={()=>onJump(c.name)}><span>{c.name}</span><small>{c.count}</small></button><details><summary aria-label={'管理大类 '+c.name}>⋯</summary><div className="category-menu"><button disabled={busy} onClick={e=>{edit(c.name);e.currentTarget.closest('details')?.removeAttribute('open');}}>重命名</button><button disabled={busy} onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');setEditing(null);setError('');setTarget('');if(c.count){setDeleting(c.name);}else{void remove(c.name);}}}>删除大类</button></div></details></div>)}</div></nav>{deleting!==null?<form className="category-form" onSubmit={e=>{e.preventDefault();void remove(deleting,target);}}><strong>删除“{deleting}”</strong><p>知识会保留，请选择移入的大类。</p><label>移动到<select aria-label="删除大类后移动到" value={target} onChange={e=>setTarget(e.target.value)}><option value="">请选择大类</option>{categories.filter(c=>c.name!==deleting).map(c=><option key={c.name} value={c.name}>{c.name}</option>)}</select></label>{categories.length===1?<p>请先取消并添加一个接收知识的大类。</p>:null}<button disabled={busy||!target}>移动并删除大类</button><button type="button" disabled={busy} onClick={()=>{setDeleting(null);setError('');}}>取消</button></form>:editing===null?<button className="category-add" onClick={()=>edit('')}>＋添加大类</button>:<form className="category-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await onSave(name,editing||undefined);setEditing(null);setName('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}}><label>{editing?'重命名大类':'添加大类'}<input autoFocus aria-label={editing?'新的大类名称':'大类名称'} value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><button disabled={busy||!name.trim()}>{busy?'保存中…':'保存大类'}</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>取消</button></form>}{error?<p role="alert">{error}</p>:null}</aside>;
}
