import React,{useEffect,useState,useRef} from 'react';
import {WeekRows} from './WeekRows';
import {AssistantPanel} from './AssistantPanel';
import {TaskTitleEditor} from './TaskTitleEditor';
import {TaskDateEditor} from './TaskDateEditor';
import {changed} from './interactions';
import {calendarEvent,categoryColors,inferCategory,type CalendarItem} from '../domain/plannerPresentation';
import {dateCaption,localDateKey} from '../domain/timePresentation';

export async function plannerApi<T=any>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'操作失败');if(method!=='GET')changed(d);return d;}
export function ScheduleDetail({item,onClose,onSaved}:{item:CalendarItem;onClose:()=>void;onSaved:()=>void}){
  const [draft,setDraft]=useState({...item}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const close=()=>{if(JSON.stringify(item)!==JSON.stringify(draft)&&!window.confirm('有未保存修改，确定关闭？'))return;onClose();};
  useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[draft]);
  async function save(status=draft.status){setBusy(true);try{await plannerApi('/personal/schedule/'+item.id,'PATCH',{...draft,status});onSaved();onClose();}catch(e){setError(String(e));}finally{setBusy(false);}}
  return <div className="drawer-backdrop" onClick={e=>{if(e.target===e.currentTarget)close();}}><aside className="task-drawer" role="dialog" aria-label="事项详情"><button onClick={close}>关闭详情</button><h3>固定时间事项</h3><label>标题<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>{(['start_at','end_at'] as const).map(key=><label key={key}>{key==='start_at'?'开始':'结束（跨天时填写）'}<input type="datetime-local" value={draft[key]?localDateKey(draft[key]!)+(draft[key]!.length>10?'T'+new Date(draft[key]!).toTimeString().slice(0,5):'T00:00'):''} onChange={e=>setDraft({...draft,[key]:e.target.value?new Date(e.target.value).toISOString():null})}/></label>)}<button disabled={busy} onClick={()=>void save()}>保存</button><button disabled={busy} onClick={()=>void save('completed')}>完成事项</button><button disabled={busy} onClick={()=>void save('canceled')}>取消事项</button>{error?<p role="alert">{error}</p>:null}</aside></div>;
}
export function PlannerCalendar(){
  const tray=useRef<HTMLDivElement>(null),board=useRef<HTMLDivElement>(null);
  const [split,setSplit]=useState(()=>{const n=Number(localStorage.getItem('week-planner-split'));return n>=22&&n<=50?n:35;});
  function resize(value:number){const n=Math.max(22,Math.min(50,value));setSplit(n);localStorage.setItem('week-planner-split',String(n));}
  const [tasks,setTasks]=useState<CalendarItem[]>([]),[events,setEvents]=useState<CalendarItem[]>([]),[appearance,setAppearance]=useState<any[]>([]);
  const [reviewTask,setReviewTask]=useState(''),[reviewName,setReviewName]=useState('');
  const [input,setInput]=useState(''),[message,setMessage]=useState(''),[assistant,setAssistant]=useState(false),[selected,setSelected]=useState<any>(null),[schedule,setSchedule]=useState<CalendarItem|null>(null),[date,setDate]=useState(''),[opacity,setOpacity]=useState(1),[busy,setBusy]=useState(false);
  async function refresh(){const [t,p,a]=await Promise.all([plannerApi('/tasks/planning'),plannerApi('/personal/dashboard'),plannerApi('/appearance')]);setTasks(t.tasks);setEvents(p.schedule.filter((s:CalendarItem)=>s.status==='scheduled'));setAppearance(a);}
  useEffect(()=>{void refresh().catch(e=>setMessage(e.message));const f=()=>void refresh().catch(()=>{});window.addEventListener('assistant-changed',f);window.addEventListener('storage',f);const timer=setInterval(f,15000);return()=>{clearInterval(timer);window.removeEventListener('assistant-changed',f);window.removeEventListener('storage',f);};},[]);
  async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);try{await fn();await refresh();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  async function openTask(id:string){setSelected(await plannerApi('/tasks/'+id+'/details'));}
  const entries=[...tasks.map(t=>calendarEvent(t,'task',appearance.find(a=>a.item_id===t.id))),...events.map(t=>calendarEvent(t,'schedule',appearance.find(a=>a.item_id===t.id)))].filter(Boolean) as any[];
  if(assistant)return <main className="planner-assistant-shell"><button onClick={()=>setAssistant(false)}>返回周计划</button><AssistantPanel initialQuestion={reviewTask?'复盘：'+reviewName:undefined} initialReviewTask={reviewTask||undefined}/></main>;
  return <main className="calendar-widget"><div className="planner-drag-strip" title="拖动窗口"/><header className="calendar-widget-toolbar"><form onSubmit={e=>{e.preventDefault();if(input.trim())void act(async()=>{await plannerApi('/tasks','POST',{task:{title:input,startAt:date||null}});setInput('');setDate('');});}}><input placeholder="输入一个任务……" value={input} onChange={e=>setInput(e.target.value)}/>{date?<button type="button" onClick={()=>setDate('')}>{date} ×</button>:null}<button disabled={busy}>添加</button></form><button onClick={()=>void act(async()=>{const r=await plannerApi('/desktop/open-main','POST');if(!r.supported)window.open('/','_blank');})}>打开主面板</button><button onClick={()=>{setReviewTask('');setAssistant(true);}}>助理</button><details><summary>⚙</summary><label>透明度<input type="range" min="0.7" max="1" step="0.05" value={opacity} onChange={e=>{const value=Number(e.target.value);setOpacity(value);void plannerApi('/desktop/widget/opacity','POST',{opacity:value});}}/></label></details></header>
    {message?<p role="status">{message}</p>:null}<div ref={board} className="calendar-widget-body" style={{'--task-column':split+'%'} as React.CSSProperties}>
    <section className="calendar-task-pane"><h3>所有任务 <small>{tasks.length}</small></h3><small>拖到右侧安排日期，点击查看详情</small><div ref={tray} className="calendar-task-list">{tasks.map(t=><button key={t.id} data-task-id={t.id} draggable onDragStart={e=>e.dataTransfer.setData('application/x-planner-item',JSON.stringify({kind:'task',id:t.id}))} onClick={()=>void openTask(t.id)}><span className="calendar-task-name"><i className="calendar-dot" style={{background:appearance.find(a=>a.item_id===t.id)?.color||categoryColors[inferCategory(t.title)]}}/><span>{t.starred?'★ ':''}{t.title}</span></span><small>{t.start_at?'计划 '+dateCaption(t.start_at):'未安排'}{t.deadline_at?' · 截止 '+dateCaption(t.deadline_at):''}</small></button>)}{!tasks.length?<p>暂无未完成任务</p>:null}</div></section>
    <div className="calendar-column-splitter" role="separator" aria-label="调整左右栏宽度" aria-orientation="vertical" aria-valuenow={Math.round(split)} aria-valuemin={22} aria-valuemax={50} tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();resize(split+(e.key==='ArrowRight'?2:-2));}}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)&&board.current){const r=board.current.getBoundingClientRect();resize((e.clientX-r.left)/r.width*100);}}} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)}/>
    <section className="calendar-week-pane">
    <WeekRows entries={entries} onDate={day=>{setDate(day);document.querySelector<HTMLInputElement>('.calendar-widget-toolbar input')?.focus();}} onOpen={(kind,item)=>{if(kind==='task')void openTask(item.id);else setSchedule(item);}} onComplete={(kind,item)=>void act(async()=>{await plannerApi(kind==='task'?'/tasks/'+item.id+'/complete':'/personal/schedule/'+item.id,kind==='task'?'POST':'PATCH',kind==='task'?{}:{status:'completed'});})} onMove={(kind,id,day,fromDay)=>void act(async()=>{if(kind==='task'){const item=tasks.find(t=>t.id===id);if(!item)throw new Error('任务已更新，请刷新。');const start=item.start_at&&item.start_at.length>10?day+'T'+new Date(item.start_at).toTimeString().slice(0,8):day;await plannerApi('/tasks/'+id,'PATCH',{task:{startAt:start}});}else{const item=events.find(t=>t.id===id);if(!item?.start_at)return;const delta=Math.round((Date.parse(day+'T12:00:00')-Date.parse((fromDay||localDateKey(item.start_at))+'T12:00:00'))/86400000);const shift=(value:string)=>{const d=new Date(value.length===10?value+'T12:00:00':value);d.setDate(d.getDate()+delta);return value.length===10?localDateKey(d):d.toISOString();};await plannerApi('/personal/schedule/'+id,'PATCH',{start_at:shift(item.start_at),end_at:item.end_at?shift(item.end_at):null});}})}/>

    </section></div>{schedule?<ScheduleDetail item={schedule} onClose={()=>setSchedule(null)} onSaved={()=>void refresh()}/>:null}
    {selected?<div className="drawer-backdrop" onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}}><aside className="task-drawer" role="dialog" aria-label="任务详情"><button onClick={()=>setSelected(null)}>关闭详情</button><h3><TaskTitleEditor key={selected.task.id} task={selected.task} onSaved={()=>{void openTask(selected.task.id);void refresh();}}/></h3><button onClick={()=>{setReviewTask(selected.task.id);setReviewName(selected.task.title);setSelected(null);setAssistant(true);}}>复盘这件事</button><TaskDateEditor task={selected.task} onSaved={()=>void openTask(selected.task.id)}/><label>类型<select value={appearance.find(a=>a.item_id===selected.task.id)?.category||inferCategory(selected.task.title)} onChange={e=>{const category=e.target.value;void act(async()=>{await plannerApi('/appearance/'+selected.task.id,'PATCH',{category,color:categoryColors[category]});});}}>{Object.keys(categoryColors).map(c=><option key={c}>{c}</option>)}</select></label><label>颜色<input type="color" value={appearance.find(a=>a.item_id===selected.task.id)?.color||categoryColors[inferCategory(selected.task.title)]} onChange={e=>{const color=e.target.value;void act(async()=>{await plannerApi('/appearance/'+selected.task.id,'PATCH',{color});});}}/></label>{selected.steps?.map((s:any)=><button className="planner-subtask" key={s.id} onClick={()=>void act(async()=>{await plannerApi('/tasks/steps/'+s.id,'PATCH',{completed:!s.completed});await openTask(selected.task.id);})}>{s.completed?'✓':'○'} {s.title}</button>)}{selected.points?.map((p:any)=><p key={p.id}>{p.content}</p>)}<p>{selected.task.notes}</p><button onClick={()=>void act(async()=>{await plannerApi('/tasks/'+selected.task.id+'/complete','POST',{});setSelected(null);})}>完成任务</button></aside></div>:null}
  </main>;
}
