import React,{useEffect,useState,useRef} from 'react';
import {captureKey,changed} from './interactions';
import {Markdown} from './KnowledgeMap';

const labels={goal:'原本目标',outcome:'实际情况',reason:'原因判断',nextStep:'下次调整',lesson:'可保留的经验'};
async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api/assistant/reviews'+path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'操作失败');if(method!=='GET')changed();return d;}
export function ReviewPanel({title,taskId,history=false,onClose}:{title?:string;taskId?:string;history?:boolean;onClose:()=>void}){
 const requestId=useRef(crypto.randomUUID());
 const [review,setReview]=useState<any>(null),[list,setList]=useState<any[]>([]),[text,setText]=useState(''),[draft,setDraft]=useState<any>(null),[name,setName]=useState(''),[category,setCategory]=useState('复盘经验'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const dirty=review&&draft&&(JSON.stringify(draft)!==JSON.stringify(review.draft)||name!==review.title);
 function load(r:any){setReview(r);setDraft(r.draft);setName(r.title);setText('');}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{let active=true;setBusy(true);const request=history?api(''):api('','POST',{title:(title||'本周复盘').slice(0,180),prompt:title,scope:/本周|这周|一周|周复盘/.test(title||'本周复盘')?'week':'event',taskId,requestId:requestId.current});void request.then(r=>{if(active){if(history)setList(r);else load(r);}}).catch(e=>{if(active)setError(String(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[]);
 function close(){if(busy)return;if((dirty||text.trim())&&!window.confirm('还有未保存的输入，确定返回？'))return;onClose();}
 async function respond(finish=false){if(dirty){setError('请先保存修改后的复盘卡片，再继续对话。');return;}await run(async()=>load(await api('/'+review.id+'/respond','POST',{revision:review.revision,text,finish})));}
 return <section className="review-panel" aria-label="复盘"><header><button disabled={busy} onClick={close}>返回助理</button><h3>{history&&!review?'复盘记录':'一起复盘'}</h3></header>{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{busy?<p role="status">处理中…</p>:null}
 {!review&&history?<div className="review-history">{list.length?list.map(r=><button key={r.id} onClick={()=>void run(async()=>load(await api('/'+r.id)))}><strong>{r.title}</strong><small>{new Date(r.updated_at).toLocaleDateString()} · {r.status==='saved'?'已保存':'草稿'}</small></button>):<p>还没有复盘记录。</p>}</div>:null}
 {review?<><details className="review-facts" open><summary>已有记录（可核对）</summary>{review.context.tasks.length?review.context.tasks.map((t:any)=><p key={t.id}>{t.title} · {t.status==='completed'?'已完成':'未完成'}{t.start_at?' · 计划 '+t.start_at.slice(0,10):''}</p>):<p>没有匹配的任务记录，可以直接描述发生的事情。</p>}{review.context.details?.points.map((p:any)=><p key={p.id}>{p.content}</p>)}{review.context.notes.length?<details><summary>相关笔记 {review.context.notes.length} 条</summary>{review.context.notes.map((n:any)=><p key={n.id}>{n.raw_text}</p>)}</details>:null}{review.context.previousReviews?.length?<details><summary>之前的相关复盘 {review.context.previousReviews.length} 条</summary>{review.context.previousReviews.map((r:any)=><p key={r.id}>{r.title}</p>)}</details>:null}<small>{review.context.limitations}</small></details>
 <div className="review-dialogue">{[...review.messages].reverse().map((m:any,i:number)=><div key={i} className={'conversation-message '+m.role}><strong>{m.role==='user'?'你':'助理'}</strong><Markdown text={m.content}/></div>)}</div>
 <form onSubmit={e=>{e.preventDefault();void respond();}}><textarea aria-label="复盘补充" placeholder="说说实际结果、遇到的问题，或这次有效的方法……" value={text} disabled={busy} onChange={e=>setText(e.target.value)} onKeyDown={e=>captureKey(e,setText)}/><div className="assistant-controls"><small>Enter 发送 · Ctrl+Enter 换行</small><button disabled={busy||!text.trim()}>发送补充</button><button type="button" disabled={busy} onClick={()=>void respond(true)}>直接整理复盘</button></div></form>
 {review.messages.length>1||review.status==='saved'?<div className="review-card"><h3>复盘卡片</h3><label>复盘标题<input aria-label="复盘标题" value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><div className="review-fields">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea aria-label={label} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} disabled={busy} rows={2}/></label>)}</div><button disabled={busy} onClick={()=>void run(async()=>{load(await api('/'+review.id,'PATCH',{revision:review.revision,title:name,draft}));setNotice('复盘已保存，可在“复盘记录”中继续查看。');})}>保存复盘</button>
 <div className="review-actions"><label>经验保存大类<input aria-label="经验保存大类" value={category} onChange={e=>setCategory(e.target.value)}/></label>{(['knowledge','task'] as const).map(kind=><button key={kind} disabled={busy||dirty||review.status!=='saved'||!draft[kind==='task'?'nextStep':'lesson'].trim()||review.exports.some((e:any)=>e.kind===kind)} onClick={()=>void run(async()=>{await api('/'+review.id+'/export','POST',{kind,category,revision:review.revision});load(await api('/'+review.id));setNotice(kind==='task'?'已加入待办任务。':'已存入知识库，并保留复盘来源。');})}>{review.exports.some((e:any)=>e.kind===kind)?(kind==='task'?'已加入任务':'已存为经验'):(kind==='task'?'加入任务':'存为经验')}</button>)}</div><small>先保存复盘，再选择是否存为经验或加入任务。</small></div>:null}
 </>:null}</section>;
}
