import React,{useState} from 'react';
import {localDateKey} from '../domain/timePresentation';

export function WeekRows({entries,onDate,onOpen,onComplete,onMove}:{entries:any[];onDate:(day:string)=>void;onOpen:(kind:string,item:any)=>void;onComplete:(kind:string,item:any)=>void;onMove:(kind:string,id:string,day:string,fromDay?:string)=>void}){
 const [offset,setOffset]=useState(0),[over,setOver]=useState('');
 const today=localDateKey(new Date()),start=new Date(today+'T12:00:00');start.setDate(start.getDate()-(start.getDay()+6)%7+offset*7);
 const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return localDateKey(d);});
 return <div className="week-rows-calendar"><header className="week-rows-toolbar"><div><button aria-label="上一周" onClick={()=>setOffset(offset-1)}>‹</button><button aria-label="下一周" onClick={()=>setOffset(offset+1)}>›</button><button onClick={()=>setOffset(0)}>今天</button></div><strong>{days[0]} — {days[6]}</strong></header><div className="week-rows">{days.map((day,i)=><section key={day} data-date={day} className={'week-day-row'+(day===today?' is-today':'')+(over===day?' drag-over':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-planner-item')){e.preventDefault();e.dataTransfer.dropEffect='move';setOver(day);}}} onDragLeave={()=>setOver('')} onDrop={e=>{e.preventDefault();setOver('');try{const data=JSON.parse(e.dataTransfer.getData('application/x-planner-item'));if(['task','schedule'].includes(data.kind)&&typeof data.id==='string')onMove(data.kind,data.id,day,data.fromDay);}catch{/* Ignore foreign drags. */}}}>
  <button className="week-day-label" onClick={()=>onDate(day)} title="在这天添加任务"><strong>周{'一二三四五六日'[i]}</strong><small>{day.slice(5).replace('-','/')}</small>{day===today?<span>今天</span>:null}</button>
  <div className="week-day-items" onDoubleClick={e=>{if(e.target===e.currentTarget)onDate(day);}}>{entries.filter(e=>e.start<=day&&(e.end?day<e.end:e.start===day)).map(entry=>{const {kind,item,time,span,color}=entry.extendedProps;return <div key={entry.id} draggable onDragStart={e=>e.dataTransfer.setData('application/x-planner-item',JSON.stringify({kind,id:item.id,fromDay:day}))} className={'week-row-event '+(span?'span-event':'dot-event')} style={span?{background:color}:undefined}><button className="week-event-open" onClick={()=>onOpen(kind,item)}>{!span?<i className="calendar-dot" style={{background:color}}/>:null}<span>{time?time+' ':''}{item.title}{span?'（跨天）':''}</span></button><button className="week-event-complete" aria-label={'完成 '+item.title} onClick={()=>onComplete(kind,item)}>✓</button></div>;})}{!entries.some(e=>e.start<=day&&(e.end?day<e.end:e.start===day))?<button className="empty-day" onClick={()=>onDate(day)}>＋ 添加事项</button>:null}</div>
 </section>)}</div></div>;
}
